# Generated by Django 4.2.13 on 2024-05-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='profile_path',
            field=models.TextField(null=True),
        ),
    ]
